version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "monthly" # Can also be "weekly" or "monthly"
    open-pull-requests-limit: 10
